not sure how this will work with subdirectories
https://stackoverflow.com/questions/1139271/makefiles-with-source-files-in-different-directories

looks like we will be using VPATH

or

we can create a makefile in each subdirectory and recursively make on the top level